###############################################################################
# Jekyll Configuration
highlighter: rouge
markdown: kramdown
permalink: /:title.html
#paginate: 5
port: 3000
safe: true
language: 'en-uk'
plugins: [jekyll-feed]

###############################################################################
# Page Personal Details
url: http://127.0.0.1:3000/
baseurl: /
author: Taapas Agrawal
title: Taapas Agrawal | Welcome to my homepage
description: Personal Landing Page
avatar: taapas.jpg

# Contacts
email: taapas2897@gmail.com

# Upon Request for Phone, Skype, Hangouts, etc.
urequest: Upon request

# Github
username: taapasX28
